version: '3'

services:
  app:
    build:
      context: ./
      dockerfile: dockerfile.dev
    image: public.ecr.aws/d5a3o9l1/hnn:dev
    ports:
      - '3100:3100'
    environment:
      NODE_ENV: .dev.env

    command: npm run start:dev

  app-prod:
    build:
      context: ./
      dockerfile: dockerfile.prod
    image: public.ecr.aws/d5a3o9l1/hnn:prod

    environment:
      NODE_ENV: .prod.env
    ports:
      - '3000:3000'
    command: npm run start:prod
