version: '3'

services:
  app:
    build:
      context: ./
      dockerfile: dockerfile.dev
    image: public.ecr.aws/d5a3o9l1/hnn-test:dev
    ports:
      - '3100:3100'

    command: npm run start:dev
