FROM --platform=linux/amd64 node:alpine AS development

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY .dev.env .

ENV $(cat .dev.env | xargs)

COPY . .

CMD [ "npm", "run", "start:dev" ]
