FROM --platform=linux/amd64 node:alpine AS production

WORKDIR /app

COPY package*.json ./

RUN npm install --only=production

COPY .dev.env /

RUN mkdir src

COPY src src

CMD [ "npm", "run", "start:prod" ]
